### ISSUE TITLE
0.9.0 にて、/fn spectate コマンドを実行したり、参加プレイヤーが死亡したりすると、エラーが起こって観客席に移動しない

### ISSUE THREAD

**Issue by ucchyocean** [ucchyocean/Five-Nights-at-Freddy-s-in-Minecraft#25]
スタックトレースは下記のとおり。

<pre>
[17:57:44] [Server thread/INFO]: Player300 issued server command: /fn spectate
[17:57:44] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'fn' in plugin FiveNightAtFreddysInMinecraft v0.9.0
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:460) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at org.bitbucket.ucchy.fnafim.game.GameSession.joinSpectator(GameSession.java:1171) ~[?:?]
    at org.bitbucket.ucchy.fnafim.FNAFIMCommand.spectateCommand(FNAFIMCommand.java:260) ~[?:?]
    at org.bitbucket.ucchy.fnafim.FNAFIMCommand.onCommand(FNAFIMCommand.java:50) ~[?:?]
    at org.bitbucket.ucchy.fnafim.FiveNightsAtFreddysInMinecraft.onCommand(FiveNightsAtFreddysInMinecraft.java:105) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    ... 15 more
</pre>

**Comment by ucchyocean** [comment]
問題は、v0.7.2 のときの issue #20 に関する修正内容にあり、spectate とすべきところを spactate と綴りミスしているため、Location が取得できず null になり、テレポートが実行されない。
https://github.com/ucchyocean/Five-Nights-at-Freddy-s-in-Minecraft/blob/2137e8f4f9d3bcfbe785cad42368cd53e9b3a26d/src/main/java/org/bitbucket/ucchy/fnafim/LocationManager.java#L205

**Comment by ucchyocean** [comment]
Fixed
動作確認OK
